### ISSUE TITLE
Cannot configure values of different types in 'settings' input variable due to map(any) type

### ISSUE THREAD

**Issue by chgerkens** [DNXLabs/terraform-aws-eks-cloudwatch-logs#5]
### Description. What happened?

If you mix different values like strings and list e.g. a) override configure image.repository (string value) and b) add tolerations (list/array value), terraform fails with 
`The given value is not suitable for child module variable "settings" defined at .terraform/modules/cloudwatch_logs/_variables.tf:97,1-20: all map elements must have the same type.`

The reason is how terraform handles variable typ map(any): https://www.terraform.io/language/expressions/type-constraints
> The keyword map is a shorthand for map(any), which accepts any element type as long as every element is the same type. This is for compatibility with older configurations; for new code, we recommend using the full form.

### Steps to reproduce

see description

### Expected behavior

Input variable `settings` is of type `any` so that values of different type can be configured. 
See DNXLabs/eks-lb-controller as a reference: https://registry.terraform.io/modules/DNXLabs/eks-lb-controller/aws/latest

### Actual behavior

Terraform fails with `: all map elements must have the same type.`

### Occurrence

Sometimes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caiovfernandes** [comment]
Hi @chgerkens , thanks for reporting this issue.

**We solve it on the latest release of this module [v0.1.4](https://github.com/DNXLabs/terraform-aws-eks-cloudwatch-logs/releases/tag/0.1.4).**
